create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  guide_detail text[],
  expert_target text[],
  category text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

insert into public.programs (slug, title, description, guide_detail, expert_target, category, is_active)
values
  (
    'diet',
    'Program Diet & Nutrisi',
    'Program yang membantu Anda mengatur pola makan secara lebih terarah dan konsisten.',
    array[
      'Tetapkan target kalori harian yang realistis.',
      'Pilih makanan dengan porsi seimbang dan rutin minum air.',
      'Pantau asupan protein, serat, dan sayur setiap hari.'
    ],
    array[
      'Menurunkan berat badan secara bertahap dan aman.',
      'Meningkatkan kualitas pola makan sehari-hari.',
      'Membantu menjaga energi tetap stabil.'
    ],
    'diet',
    true
  ),
  (
    'fitness',
    'Program Kebugaran',
    'Program yang fokus pada aktivitas fisik ringan sampai menengah untuk menjaga stamina.',
    array[
      'Lakukan olahraga ringan secara rutin, misalnya jalan kaki atau stretching.',
      'Sesuaikan intensitas latihan dengan kondisi tubuh.',
      'Jaga jadwal istirahat agar tubuh pulih dengan baik.'
    ],
    array[
      'Meningkatkan stamina dan kebugaran tubuh.',
      'Membantu menjaga postur dan fleksibilitas.',
      'Mendorong kebiasaan aktif secara konsisten.'
    ],
    'fitness',
    true
  ),
  (
    'wellness',
    'Program Kesehatan Holistik',
    'Program yang membantu Anda menjaga pola hidup lebih sehat secara menyeluruh.',
    array[
      'Prioritaskan tidur yang cukup dan pola makan teratur.',
      'Kelola stres dengan rutinitas yang menenangkan.',
      'Perhatikan tanda tubuh dan lakukan evaluasi berkala.'
    ],
    array[
      'Meningkatkan kualitas tidur dan istirahat.',
      'Membantu mengurangi stres secara bertahap.',
      'Mendorong gaya hidup yang lebih seimbang.'
    ],
    'wellness',
    true
  )
on conflict (slug) do nothing;
